# Inspired choices from: https://github.com/UFO-101/auto-circuit/blob/main/.pre-commit-config.yaml
# This is all using the framework defined here: https://pre-commit.com.
# Basicaly, you set up a YAML file and run a certain "install" command
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    # Do not commit large files
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=2000']
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: [ --autofix, --no-sort-keys ]
  # Formatting
  - repo: https://github.com/psf/black
    rev: "22.6.0"
    hooks:
      - id: black
  # Linting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.280
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [ --fix, --exit-non-zero-on-fix ]
  # Catch mispelled words
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        args: [-L, "ans,fpr"]  # Allow extra words
        additional_dependencies:
          # Includes a parser for .toml files so we include our pyproject and other high-level files
          - tomli
  - repo: local
    hooks:
    # Type-checking
    - id: pyright
      name: pyright
      stages: [commit]
      types: [python]
      entry: pyright
      language: system
      pass_filenames: false
      always_run: true
    # Running unit (etc...) tests
    - id: pytest
      name: pytest
      stages: [commit]
      types: [python]
      entry: pytest
      language: system
      pass_filenames: false
      always_run: true
      verbose: true  # Show pytest output
      args: [ -s ]  # Make pytest output stdout
# Exclude these files from all our hooks from above
exclude: ^(poetry\.lock)
